name: harmony_app
description: This is a Hrmony app for CS307

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  spotify_sdk:

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.0.3
  cloud_firestore: ^3.4.9
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  loading_overlay: ^0.3.0
  firestore_search: ^0.1.9
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  firebase_storage: ^10.3.11
  flutter_profile_picture: ^2.0.0
  flutter_speed_dial: ^6.2.0
  image_picker: ^0.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo.png


  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800

